/**
 * India Geographic Dataset & Sankara Eye Hospital Units
 * Provides cascading State -> District mapping and standard Sankara hospital branches.
 */

export interface StateDistricts {
  state: string;
  districts: string[];
}

export const SANKARA_UNITS = [
  "Sankara Eye Hospital, Bangalore (Kundalahalli)",
  "Sankara Eye Hospital, Bangalore (Jayanagar)",
  "Sankara Eye Hospital, Coimbatore (RS Puram)",
  "Sankara Eye Hospital, Coimbatore (Saravanampatti)",
  "Sankara Eye Hospital, Guntur (Andhra Pradesh)",
  "Sankara Eye Hospital, Shimoga (Karnataka)",
  "Sankara Eye Hospital, Anand (Gujarat)",
  "Sankara Eye Hospital, Kanpur (Uttar Pradesh)",
  "Sankara Eye Hospital, Jaipur (Rajasthan)",
  "Sankara Eye Hospital, Indore (Madhya Pradesh)",
  "Sankara Eye Hospital, Ludhiana (Punjab)",
  "Sankara Eye Hospital, Panvel (Maharashtra / Mumbai)",
  "Sankara Eye Hospital, Hyderabad (Telangana)",
  "Sankara Eye Hospital, Varanasi (Uttar Pradesh)",
  "Medical Headquarters (MHQ), Coimbatore",
  "Sankara College of Optometry",
  "Other Unit / External Institution",
];

export const INDIA_STATES_DISTRICTS: StateDistricts[] = [
  {
    state: "Karnataka",
    districts: [
      "Bangalore Urban",
      "Bangalore Rural",
      "Shimoga (Shivamogga)",
      "Mysore (Mysuru)",
      "Dakshina Kannada (Mangalore)",
      "Udupi",
      "Belgaum (Belagavi)",
      "Dharwad (Hubli)",
      "Tumkur (Tumakuru)",
      "Bellary (Ballari)",
      "Davangere",
      "Mandya",
      "Hassan",
      "Kolar",
      "Chikkaballapur",
      "Chitradurga",
      "Bagalkot",
      "Bidar",
      "Bijapur (Vijayapura)",
      "Chamarajanagar",
      "Chikkamagaluru",
      "Gadag",
      "Gulbarga (Kalaburagi)",
      "Haveri",
      "Kodagu",
      "Koppal",
      "Raichur",
      "Ramanagara",
      "Uttara Kannada",
      "Yadgir",
    ],
  },
  {
    state: "Tamil Nadu",
    districts: [
      "Coimbatore",
      "Chennai",
      "Madurai",
      "Salem",
      "Tiruchirappalli (Trichy)",
      "Tirunelveli",
      "Erode",
      "Tiruppur",
      "Vellore",
      "Kanchipuram",
      "Chengalpattu",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Kallakurichi",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Ranipet",
      "Sivaganga",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thoothukudi",
      "Tirupathur",
      "Tiruvallur",
      "Tiruvannamalai",
      "Tiruvarur",
      "Viluppuram",
      "Virudhunagar",
    ],
  },
  {
    state: "Andhra Pradesh",
    districts: [
      "Guntur",
      "Krishna (Vijayawada)",
      "Visakhapatnam",
      "NTR District",
      "Chittoor",
      "Tirupati",
      "Kurnool",
      "Anantapur",
      "East Godavari",
      "West Godavari",
      "Kadapa (YSR)",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Vizianagaram",
      "Eluru",
      "Bapatla",
      "Palnadu",
      "Nandyal",
      "Sri Sathya Sai",
      "Annamayya",
      "Konaseema",
      "Kakinada",
      "Parvathipuram Manyam",
      "Alluri Sitharama Raju",
    ],
  },
  {
    state: "Gujarat",
    districts: [
      "Anand",
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Gandhinagar",
      "Junagadh",
      "Kheda",
      "Mehsana",
      "Bharuch",
      "Valsad",
      "Navsari",
      "Panchmahal",
      "Dahod",
      "Sabarkantha",
      "Banaskantha",
      "Kutch",
      "Amreli",
      "Surendranagar",
      "Morbi",
      "Gir Somnath",
      "Botad",
      "Porbandar",
      "Devbhoomi Dwarka",
    ],
  },
  {
    state: "Uttar Pradesh",
    districts: [
      "Kanpur Nagar",
      "Kanpur Dehat",
      "Varanasi",
      "Lucknow",
      "Agra",
      "Prayagraj (Allahabad)",
      "Noida (Gautam Buddha Nagar)",
      "Ghaziabad",
      "Meerut",
      "Bareilly",
      "Aligarh",
      "Moradabad",
      "Saharanpur",
      "Gorakhpur",
      "Faizabad (Ayodhya)",
      "Jhansi",
      "Mathura",
      "Muzaffarnagar",
      "Mirzapur",
      "Unnao",
      "Fatehpur",
      "Sitapur",
      "Hardoi",
      "Barabanki",
      "Raebareli",
    ],
  },
  {
    state: "Rajasthan",
    districts: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Bhilwara",
      "Sikar",
      "Bharatpur",
      "Pali",
      "Sri Ganganagar",
      "Jhunjhunu",
      "Chittorgarh",
      "Nagaur",
    ],
  },
  {
    state: "Madhya Pradesh",
    districts: [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa",
      "Katni",
      "Singrauli",
      "Burhanpur",
      "Khandwa",
      "Morena",
      "Bhind",
      "Chhindwara",
      "Guna",
      "Shivpuri",
      "Vidisha",
    ],
  },
  {
    state: "Punjab",
    districts: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "SAS Nagar (Mohali)",
      "Hoshiarpur",
      "Pathankot",
      "Moga",
      "Firozpur",
      "Kapurthala",
      "Sangrur",
      "Barnala",
      "Fatehgarh Sahib",
      "Fazilka",
      "Gurdaspur",
      "Faridkot",
      "Mansa",
      "Muktsar",
      "Rupnagar",
      "Tarn Taran",
    ],
  },
  {
    state: "Maharashtra",
    districts: [
      "Mumbai City",
      "Mumbai Suburban",
      "Thane",
      "Raigad (Panvel / Navi Mumbai)",
      "Pune",
      "Nagpur",
      "Nashik",
      "Aurangabad (Chhatrapati Sambhaji Nagar)",
      "Solapur",
      "Kolhapur",
      "Amravati",
      "Nanded",
      "Sangli",
      "Jalgaon",
      "Akola",
      "Latur",
      "Dhule",
      "Ahmednagar",
      "Satara",
      "Chandrapur",
    ],
  },
  {
    state: "Telangana",
    districts: [
      "Hyderabad",
      "Rangareddy",
      "Medchal-Malkajgiri",
      "Warangal",
      "Hanamkonda",
      "Khammam",
      "Karimnagar",
      "Nizamabad",
      "Mahabubnagar",
      "Nalgonda",
      "Sangareddy",
      "Siddipet",
      "Bhadradri Kothagudem",
    ],
  },
  {
    state: "Kerala",
    districts: [
      "Ernakulam (Kochi)",
      "Thiruvananthapuram",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Palakkad",
      "Malappuram",
      "Kannur",
      "Kottayam",
      "Alappuzha",
      "Idukki",
      "Pathanamthitta",
      "Kasaragod",
      "Wayanad",
    ],
  },
  {
    state: "Delhi (NCT)",
    districts: [
      "New Delhi",
      "South Delhi",
      "South East Delhi",
      "South West Delhi",
      "Central Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "East Delhi",
      "West Delhi",
      "Shahdara",
    ],
  },
  {
    state: "Haryana",
    districts: [
      "Gurugram (Gurgaon)",
      "Faridabad",
      "Panchkula",
      "Ambala",
      "Karnal",
      "Panipat",
      "Sonipat",
      "Rohtak",
      "Hisar",
      "Yamunanagar",
      "Kurukshetra",
      "Rewari",
    ],
  },
  {
    state: "West Bengal",
    districts: [
      "Kolkata",
      "North 24 Parganas",
      "South 24 Parganas",
      "Howrah",
      "Hooghly",
      "Darjeeling",
      "Paschim Medinipur",
      "Purba Medinipur",
      "Murshidabad",
      "Nadia",
      "Birbhum",
      "Burdwan",
      "Malda",
      "Jalpaiguri",
    ],
  },
  {
    state: "Bihar",
    districts: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Darbhanga",
      "Purnia",
      "Begusarai",
      "Munger",
      "Nalanda",
      "Samastipur",
      "Rohtas",
      "Saran",
    ],
  },
  {
    state: "Odisha",
    districts: [
      "Khordha (Bhubaneswar)",
      "Cuttack",
      "Puri",
      "Ganjam",
      "Baleswar (Balasore)",
      "Sambalpur",
      "Sundargarh (Rourkela)",
      "Bhadrak",
      "Mayurbhanj",
      "Angul",
    ],
  },
  {
    state: "Assam",
    districts: [
      "Kamrup Metropolitan (Guwahati)",
      "Kamrup",
      "Dibrugarh",
      "Silchar (Cachar)",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Sonitpur (Tezpur)",
    ],
  },
  {
    state: "Goa",
    districts: ["North Goa", "South Goa"],
  },
  {
    state: "Uttarakhand",
    districts: [
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Udham Singh Nagar",
      "Pauri Garhwal",
      "Almora",
    ],
  },
  {
    state: "Himachal Pradesh",
    districts: ["Shimla", "Kangra (Dharamshala)", "Mandi", "Solan", "Kullu", "Sirmaur"],
  },
  {
    state: "Jharkhand",
    districts: ["Ranchi", "East Singhbhum (Jamshedpur)", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar"],
  },
  {
    state: "Chhattisgarh",
    districts: ["Raipur", "Durg (Bhilai)", "Bilaspur", "Korba", "Rajnandgaon", "Raigarh"],
  },
  {
    state: "Jammu and Kashmir",
    districts: ["Jammu", "Srinagar", "Anantnag", "Baramulla", "Udhampur", "Kathua"],
  },
  {
    state: "Chandigarh (UT)",
    districts: ["Chandigarh"],
  },
  {
    state: "Puducherry (UT)",
    districts: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  },
  {
    state: "Other State / Union Territory",
    districts: ["Other District / Headquarters"],
  },
];

export function getDistrictsForState(stateName: string): string[] {
  if (!stateName) return [];
  const found = INDIA_STATES_DISTRICTS.find(
    (item) => item.state.toLowerCase() === stateName.trim().toLowerCase()
  );
  return found ? found.districts : ["Other District / Not Listed"];
}
