import { db, eventsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

export const SANQALP_AGENDA = [
  // ── DAY 1: 21st Sep'26 ───────────────────────────────────────────────────────
  {
    id: "sanqualp-d1-1",
    date: "2026-09-21",
    timeFrom: "09:00 AM",
    timeTo: "09:10 AM",
    title: "Welcome address and context setting",
    type: "keynote",
    speaker: "Dr Kaushik Murali",
    speakerDesignation: "President (Medical administration, Quality and Education, SEFI)",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Welcome address and context setting for the 12th SanQALP conclave.",
    output: "Context setting",
    trackHall: "Main Auditorium, Sankara Eye Hospital, Bangalore",
    topics: ["Context Setting", "SanQALP", "TQM Introduction"],
  },
  {
    id: "sanqualp-d1-2",
    date: "2026-09-21",
    timeFrom: "09:10 AM",
    timeTo: "09:30 AM",
    title: "Founder's address",
    type: "keynote",
    speaker: "Dr R V Ramani",
    speakerDesignation: "Founder & Managing Trustee, SEFI",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Highlighting TQM as a culture of continuous improvement, aligning people and processes to enhance efficiency, patient value, and excellence.",
    output: "Inspiring teams to move from vision to measurable value by making quality and continuous improvement everyone's responsibility.",
    trackHall: "Main Auditorium",
    topics: ["Leadership", "Vision to Value", "TQM Culture"],
  },
  {
    id: "sanqualp-d1-3",
    date: "2026-09-21",
    timeFrom: "09:30 AM",
    timeTo: "10:30 AM",
    title: "Journey towards excellence",
    type: "session",
    speaker: "Mr Anandakrishnan",
    speakerDesignation: "Advisor - TVS Motor Company (Seconded to IFQM) Formerly President & Group Head - HR (CHRO)",
    speakerInstitution: "TVS Motor Company / IFQM",
    description: "Exploring the key steps, practices, and mindset required to move from compliance to continuous improvement and excellence.",
    output: "Identify practical actions to strengthen quality culture and sustain a journey of continuous improvement.",
    trackHall: "Main Auditorium",
    topics: ["Operational Excellence", "Mindset", "Culture Shift"],
  },
  {
    id: "sanqualp-d1-4",
    date: "2026-09-21",
    timeFrom: "10:30 AM",
    timeTo: "10:45 AM",
    title: "Tea Break & Networking",
    type: "break_tea",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Morning refreshment break and peer networking.",
    output: "Networking & refreshment",
    trackHall: "Lobby & Dining Pavilion",
  },
  {
    id: "sanqualp-d1-5",
    date: "2026-09-21",
    timeFrom: "10:45 AM",
    timeTo: "11:30 AM",
    title: "Group exercises",
    type: "workshop",
    speaker: "Mr Anandakrishnan",
    speakerDesignation: "Advisor - TVS Motor Company (Seconded to IFQM)",
    speakerInstitution: "TVS Motor Company / IFQM",
    description: "Exploring the key steps, practices, and mindset required to move from compliance to continuous improvement and excellence through interactive group exercises.",
    output: "Identify practical actions to strengthen quality culture and sustain a journey of continuous improvement.",
    trackHall: "Main Auditorium & Breakout Tables",
    topics: ["Team Exercises", "Continuous Improvement", "Practical Actions"],
  },
  {
    id: "sanqualp-d1-6",
    date: "2026-09-21",
    timeFrom: "11:30 AM",
    timeTo: "12:10 PM",
    title: "Daily work management",
    type: "session",
    speaker: "Ms. Srini Karthikeyan",
    speakerDesignation: "Chief People Officer, SEFI",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "BSC–DWM linkage, task prioritisation, planning and execution through DWM.",
    output: "Understand the BSC-to-DWM flow and effectively plan, track and execute priorities.",
    trackHall: "Main Auditorium",
    topics: ["BSC-DWM Linkage", "Task Prioritisation", "Daily Execution"],
  },
  {
    id: "sanqualp-d1-7",
    date: "2026-09-21",
    timeFrom: "12:10 PM",
    timeTo: "01:10 PM",
    title: "Clear Communication, Safer Care: The TQM Approach",
    type: "session",
    speaker: "Dr Malini Hebbar",
    speakerDesignation: "Principal, Swastika National Business School, Mangalore, Distinguished Toastmaster",
    speakerInstitution: "Swastika National Business School",
    description: "Explore how clear, timely, and structured communication across teams can reduce errors, strengthen coordination, and support a TQM-driven culture of continuous improvement.",
    output: "Identify key communication gaps and develop practical strategies to improve information flow, teamwork, and patient safety.",
    trackHall: "Main Auditorium",
    topics: ["Patient Safety", "Clinical Communication", "Error Reduction"],
  },
  {
    id: "sanqualp-d1-8",
    date: "2026-09-21",
    timeFrom: "01:10 PM",
    timeTo: "01:25 PM",
    title: "Group Photograph",
    type: "session",
    speaker: "All Participants & Leadership",
    speakerDesignation: "Conclave Delegates & Trustees",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Official group photo with all delegates, founders, and trustees.",
    output: "Commemorative conclave photograph.",
    trackHall: "Central Courtyard / Main Stage",
  },
  {
    id: "sanqualp-d1-9",
    date: "2026-09-21",
    timeFrom: "01:25 PM",
    timeTo: "02:25 PM",
    title: "Lunch Break",
    type: "break_lunch",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Buffet lunch & networking break.",
    output: "Dining & delegate interaction",
    trackHall: "Dining Pavilion",
  },
  {
    id: "sanqualp-d1-10",
    date: "2026-09-21",
    timeFrom: "02:25 PM",
    timeTo: "03:25 PM",
    title: "Group exercises (Communication)",
    type: "workshop",
    speaker: "Dr Malini Hebbar",
    speakerDesignation: "Principal, Swastika National Business School, Mangalore, Distinguished Toastmaster",
    speakerInstitution: "Swastika National Business School",
    description: "Explore how clear, timely, and structured communication across teams can reduce errors, strengthen coordination, and support a TQM-driven culture of continuous improvement.",
    output: "Identify key communication gaps and develop practical strategies to improve information flow, teamwork, and patient safety.",
    trackHall: "Main Auditorium & Interactive Pods",
    topics: ["Simulation Exercises", "Active Listening", "Coordination"],
  },
  {
    id: "sanqualp-d1-11",
    date: "2026-09-21",
    timeFrom: "03:25 PM",
    timeTo: "04:10 PM",
    title: "Strengthening Committees, Improving Event Reporting",
    type: "session",
    speaker: "Dr Kamala Mahesh",
    speakerDesignation: "HOD - Glaucoma, SEH Shimoga, NABH Assessor",
    speakerInstitution: "Sankara Eye Hospital, Shimoga",
    description: "Strengthening committee functioning through effective meetings, meaningful event reporting, data-based review, and action-oriented follow-up.",
    output: "Enabling committees to drive timely actions, accountability, and measurable quality improvement.",
    trackHall: "Main Auditorium",
    topics: ["Committee Functioning", "Incident Reporting", "NABH Compliance"],
  },
  {
    id: "sanqualp-d1-12",
    date: "2026-09-21",
    timeFrom: "04:10 PM",
    timeTo: "04:45 PM",
    title: "Together, we create better",
    type: "workshop",
    speaker: "Dr Gokul R",
    speakerDesignation: "Practitioner Psychologist and Lead – Research Operations, SEFI",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "An activity-led experience that invites us to discover what happens when we think, act and work together. The meaning comes alive in the conversation that follows.",
    output: "A shared reflection on what creates quality and what each of us contributes to it.",
    trackHall: "Main Auditorium",
    topics: ["Organizational Psychology", "Team Synergies", "Collective Ownership"],
  },
  {
    id: "sanqualp-d1-13",
    date: "2026-09-21",
    timeFrom: "04:45 PM",
    timeTo: "05:00 PM",
    title: "Tea Break",
    type: "break_tea",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Evening high tea & refreshments.",
    output: "Refreshment",
    trackHall: "Dining Pavilion",
  },
  {
    id: "sanqualp-d1-14",
    date: "2026-09-21",
    timeFrom: "05:00 PM",
    timeTo: "07:00 PM",
    title: "Kaizen presentations",
    type: "session",
    speaker: "All participants (Units and MHq teams)",
    speakerDesignation: "Hospital Unit Representatives & Central Medical Headquarters",
    speakerInstitution: "All SEFI Units",
    description: "Presentations by Units and MHq teams. Reexplore the Kaizen approach of making small, incremental improvements by engaging employees, identifying process gaps, and eliminating waste in everyday healthcare practices.",
    output: "Best practices learning and implementation across Units. Identify improvement opportunities and apply simple Kaizen techniques to achieve measurable, sustainable improvements in quality and efficiency.",
    trackHall: "Main Auditorium",
    topics: ["Kaizen Innovations", "Lean Healthcare", "Waste Elimination", "Unit Showcase"],
  },
  {
    id: "sanqualp-d1-15",
    date: "2026-09-21",
    timeFrom: "07:00 PM",
    timeTo: "09:00 PM",
    title: "Conclave Dinner",
    type: "break_lunch",
    speaker: "All participants",
    speakerDesignation: "Delegates & Faculty",
    speakerInstitution: "SEFI",
    description: "Conclave fellowship and networking dinner.",
    output: "Fellowship & evening dinner",
    trackHall: "Banquet Lawns / Dining Hall",
  },

  // ── DAY 2: 22nd Sep'26 ───────────────────────────────────────────────────────
  {
    id: "sanqualp-d2-1",
    date: "2026-09-22",
    timeFrom: "08:00 AM",
    timeTo: "08:45 AM",
    title: "Updates on Migration from 1st edition NABH to 2nd edition NABH",
    type: "session",
    speaker: "NABH Assessors - Dr Nisha (CMO SEH, Anand) & Dr Vijay (Consultant – General Ophthalmology, SEH Guntur)",
    speakerDesignation: "NABH Assessors / Senior Clinicians",
    speakerInstitution: "SEH Anand & SEH Guntur",
    description: "Major changes from 1st edition to 2nd edition of NABH standards.",
    output: "Better compliance with standards to enhance overall quality and patient safety.",
    trackHall: "Main Auditorium",
    topics: ["NABH 2nd Edition", "Standards Migration", "Audit Readiness"],
  },
  {
    id: "sanqualp-d2-2",
    date: "2026-09-22",
    timeFrom: "08:45 AM",
    timeTo: "09:30 AM",
    title: "Superior Management through Simple Graphs",
    type: "session",
    speaker: "Mr Ramanathan",
    speakerDesignation: "Co-founder and Past President of ISQ (Indian Society for Quality)",
    speakerInstitution: "Indian Society for Quality (ISQ)",
    description: "Using simple data visualization tools to understand process variation, identify patterns, and distinguish common from special causes.",
    output: "Enabling teams to make data-driven decisions and address process variation effectively.",
    trackHall: "Main Auditorium",
    topics: ["Data Visualization", "Process Variation", "Statistical Thinking"],
  },
  {
    id: "sanqualp-d2-3",
    date: "2026-09-22",
    timeFrom: "09:30 AM",
    timeTo: "10:15 AM",
    title: "Group exercises (Superior Management through Simple Graphs)",
    type: "workshop",
    speaker: "Mr Ramanathan",
    speakerDesignation: "Co-founder and Past President of ISQ",
    speakerInstitution: "Indian Society for Quality (ISQ)",
    description: "Hands-on application using simple graphs to evaluate hospital trends and process variances.",
    output: "Practical charting and analysis skills for unit coordinators.",
    trackHall: "Main Auditorium & Work Tables",
    topics: ["Hands-on Charting", "Data Analysis", "Decision Making"],
  },
  {
    id: "sanqualp-d2-4",
    date: "2026-09-22",
    timeFrom: "10:15 AM",
    timeTo: "10:30 AM",
    title: "Tea Break",
    type: "break_tea",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Morning refreshment & networking break.",
    output: "Refreshment",
    trackHall: "Dining Pavilion",
  },
  {
    id: "sanqualp-d2-5",
    date: "2026-09-22",
    timeFrom: "10:30 AM",
    timeTo: "11:15 AM",
    title: "From Prevention to Perfection: Poka-Yoke for Safer care",
    type: "session",
    speaker: "Mr Satish",
    speakerDesignation: "Deputy General Manager, Bosch",
    speakerInstitution: "Bosch",
    description: "Understanding Poka-Yoke principles and their application in healthcare to identify potential errors and build simple mistake-proofing mechanisms into processes.",
    output: "Identify opportunities for error prevention and apply practical Poka-Yoke solutions to improve patient safety, process reliability, and quality.",
    trackHall: "Main Auditorium",
    topics: ["Poka-Yoke", "Mistake-Proofing", "Zero Errors", "Reliable Processes"],
  },
  {
    id: "sanqualp-d2-6",
    date: "2026-09-22",
    timeFrom: "11:15 AM",
    timeTo: "12:00 PM",
    title: "Group exercise (Application of Poka Yoke)",
    type: "workshop",
    speaker: "Mr Satish",
    speakerDesignation: "Deputy General Manager, Bosch",
    speakerInstitution: "Bosch",
    description: "Interactive team exercise designing mistake-proofing solutions for ophthalmic outpatient and surgical workflows.",
    output: "Formulate practical Poka-Yoke mechanisms for unit deployment.",
    trackHall: "Main Auditorium & Breakouts",
    topics: ["Poka-Yoke Workshop", "Clinical Workflow Design", "Error Prevention"],
  },
  {
    id: "sanqualp-d2-7",
    date: "2026-09-22",
    timeFrom: "12:00 PM",
    timeTo: "12:10 PM",
    title: "QAI Accreditation: Strengthening Vision Centre Quality",
    type: "session",
    speaker: "Mr Senthilraja & Mr Rajadurai. B",
    speakerDesignation: "Mr Senthilraja (Head – Outreach) & Mr Rajadurai. B (Manager CORP Community Outreach Programme, SEFI)",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Understanding QAI accreditation requirements for Vision Centres, key standards, documentation, processes, and readiness for assessment.",
    output: "Enabling Vision Centres to achieve accreditation readiness through standardised processes, compliance, and continuous quality improvement.",
    trackHall: "Main Auditorium",
    topics: ["Vision Centres", "QAI Accreditation", "Primary Eye Care Quality"],
  },
  {
    id: "sanqualp-d2-8",
    date: "2026-09-22",
    timeFrom: "12:10 PM",
    timeTo: "01:00 PM",
    title: "Updation of existing policies",
    type: "workshop",
    speaker: "All SEFI participants",
    speakerDesignation: "Cross-functional Quality Teams",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Updation of policies across departments and hospital branches.",
    output: "Streamlining of policies towards ensuring standardized patient care.",
    trackHall: "Main Auditorium & Department Tables",
    topics: ["Policy Updation", "Clinical Protocols", "Standard Operating Procedures"],
  },
  {
    id: "sanqualp-d2-9",
    date: "2026-09-22",
    timeFrom: "01:00 PM",
    timeTo: "02:00 PM",
    title: "Lunch Break",
    type: "break_lunch",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Conclave lunch.",
    output: "Dining & discussion",
    trackHall: "Dining Pavilion",
  },
  {
    id: "sanqualp-d2-10",
    date: "2026-09-22",
    timeFrom: "02:00 PM",
    timeTo: "02:40 PM",
    title: "Continuation of policies updation",
    type: "workshop",
    speaker: "All SEFI participants",
    speakerDesignation: "Cross-functional Quality Teams",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Deep-dive continuation of policy standardization and departmental alignment.",
    output: "Streamlining of policies towards ensuring standardized patient care.",
    trackHall: "Main Auditorium",
    topics: ["Policy Finalization", "Standardization", "Consensus"],
  },
  {
    id: "sanqualp-d2-11",
    date: "2026-09-22",
    timeFrom: "02:40 PM",
    timeTo: "03:30 PM",
    title: "From Planning to Action : PDCA for Quality outcomes",
    type: "session",
    speaker: "Mr Nagaraj Kanna",
    speakerDesignation: "Heading International business quality, and TVS / BMW collaboration projects Quality, TVS Motors",
    speakerInstitution: "TVS Motors",
    description: "PDCA cycle as a structured framework for planning, executing, checking, and acting to drive continuous quality improvement.",
    output: "Atleast 3 PDCAs documented as part of continuous improvements.",
    trackHall: "Main Auditorium",
    topics: ["PDCA Cycle", "Quality Outcomes", "Actionable Frameworks"],
  },
  {
    id: "sanqualp-d2-12",
    date: "2026-09-22",
    timeFrom: "03:30 PM",
    timeTo: "04:15 PM",
    title: "Group exercises (Application of PDCA)",
    type: "workshop",
    speaker: "Mr Nagaraj Kanna",
    speakerDesignation: "Heading International business quality, and TVS / BMW collaboration projects Quality, TVS Motors",
    speakerInstitution: "TVS Motors",
    description: "PDCA cycle as a structured framework for planning, executing, checking, and acting to drive continuous quality improvement through hands-on group work.",
    output: "Documenting PDCAs as part of continuous improvements.",
    trackHall: "Main Auditorium & Work Tables",
    topics: ["PDCA Exercises", "Documentation", "Project Milestones"],
  },
  {
    id: "sanqualp-d2-13",
    date: "2026-09-22",
    timeFrom: "04:15 PM",
    timeTo: "04:30 PM",
    title: "Tea Break",
    type: "break_tea",
    speaker: "",
    speakerDesignation: "",
    speakerInstitution: "",
    description: "Afternoon tea & refreshments.",
    output: "Refreshment",
    trackHall: "Dining Pavilion",
  },
  {
    id: "sanqualp-d2-14",
    date: "2026-09-22",
    timeFrom: "04:30 PM",
    timeTo: "04:50 PM",
    title: "Key learnings & way forward",
    type: "keynote",
    speaker: "Mr Bharath (President, SEFI) & Dr Kaushik (President, SEFI)",
    speakerDesignation: "Leadership, Sankara Eye Foundation India",
    speakerInstitution: "Sankara Eye Foundation India",
    description: "Consolidation of key insights from all sessions and identification of actionable opportunities for implementation across units.",
    output: "Clear action plan to translate quality learnings into measurable improvements in patient safety, operational excellence, and TQM practices.",
    trackHall: "Main Auditorium",
    topics: ["Strategic Roadmap", "Unit Action Plans", "Leadership Vision"],
  },
  {
    id: "sanqualp-d2-15",
    date: "2026-09-22",
    timeFrom: "04:50 PM",
    timeTo: "05:00 PM",
    title: "Feedback & Closing",
    type: "session",
    speaker: "All participants",
    speakerDesignation: "Conclave Delegates & Committee",
    speakerInstitution: "SEFI",
    description: "Program feedback, evaluation, and valedictory close.",
    output: "Continuous improvement feedback and formal closing.",
    trackHall: "Main Auditorium",
    topics: ["Evaluation", "Feedback", "Valedictory"],
  },
];

async function seedSanqualp() {
  console.log("🚀 Seeding 12th SanQALP Conclave at Sankara Bangalore...");

  const slug = "sanqualp-bangalore";
  const title = "12th SanQALP Conclave";
  const theme = "From Vision to Value: Improving quality and operational efficiency through TQM";
  const objective = "To integrate TQM principles across people, processes, and performance to drive improvement, efficiency, and value creation.";
  const description = `${theme}. ${objective} The 12th SanQALP Conclave brings together clinical leaders, hospital administrators, nursing leadership, and quality champions across all Sankara Eye Hospital units.`;
  const shortDescription = "12th SanQALP Conclave on 21st & 22nd September 2026 at Sankara Eye Hospital, Bangalore. Theme: From Vision to Value (TQM). Internal staff only.";

  const eventPayload = {
    slug,
    title,
    eventType: "internal_staff",
    description,
    shortDescription,
    venue: "Sankara Eye Hospital, Bangalore",
    city: "Bangalore",
    locationMapUrl: "https://maps.google.com/?q=Sankara+Eye+Hospital+Varthur+Main+Road+Kundalahalli+Bangalore",
    startDate: "2026-09-21",
    endDate: "2026-09-22",
    timeFrom: "09:00 AM",
    timeTo: "07:00 PM",
    isPaid: false,
    registrationFee: 0,
    currency: "INR",
    requiresApproval: false,
    registrationOpen: false, // NO option for registration - internal staff only
    maxCapacity: 350,
    enableAttendance: true,
    attendanceDaysCount: 2,
    enableFood: true,
    enableGoodies: false,
    enableGoogleWallet: false,
    organizerName: "Sankara Eye Care Institutions (SEFI)",
    organizerEmail: "quality@sankaraeye.in",
    organizerPhone: "+91 80 2854 2727",
    spocName: "Quality Assurance Committee",
    spocDesignation: "SanQALP Conclave Secretariat",
    spocEmail: "quality@sankaraeye.in",
    spocPhone: "+91 80 2854 2728",
    cancellationPolicy: "Internal staff conclave. Participation is by institutional delegation and nomination across Sankara Eye Hospital units.",
    requireDocumentUpload: false,
    groupRegistrationEnabled: false,
    themeColor: "#0F172A", // Slate/Navy
    accentColor: "#3B82F6", // Professional Blue
    badgeSubtitle: "12TH SANQALP CONCLAVE · BANGALORE",
    badgeFooterText: "Sankara Quality Assurance Learning Program · Internal Staff",
    agendaJson: JSON.stringify(SANQALP_AGENDA),
    pricingTiersJson: JSON.stringify([
      {
        id: "internal_staff",
        name: "Internal Staff Delegate",
        role: "delegate",
        price: 0,
        earlyBirdPrice: 0,
        description: "Official internal delegation pass for nominated Sankara Eye Hospital staff.",
        inclusions: ["All TQM Scientific Tracks & Workshops", "Conclave Delegate Kit", "Hospitality & Dining (All 2 Days)"],
        popular: true,
      },
    ]),
    status: "published",
  };

  // Check if either slug exists
  const [existingBySlug] = await db
    .select()
    .from(eventsTable)
    .where(eq(eventsTable.slug, slug));

  const [existingDummy] = await db
    .select()
    .from(eventsTable)
    .where(eq(eventsTable.slug, "sankarasanqualp"));

  if (existingBySlug) {
    await db
      .update(eventsTable)
      .set({
        ...eventPayload,
        updatedAt: new Date(),
      })
      .where(eq(eventsTable.id, existingBySlug.id));
    console.log(`✅ Updated existing SanQALP event (ID: ${existingBySlug.id}, Slug: ${slug})`);
  } else if (existingDummy) {
    await db
      .update(eventsTable)
      .set({
        ...eventPayload,
        updatedAt: new Date(),
      })
      .where(eq(eventsTable.id, existingDummy.id));
    console.log(`✅ Updated existing draft event ID: ${existingDummy.id} to SanQALP (Slug: ${slug})`);
  } else {
    const [inserted] = await db
      .insert(eventsTable)
      .values(eventPayload)
      .returning();
    console.log(`✅ Successfully seeded new 12th SanQALP Conclave (ID: ${inserted.id}, Slug: ${slug})`);
  }

  console.log(`🎯 Total agenda sessions populated: ${SANQALP_AGENDA.length} slots across 2 days.`);
}

if (process.argv[1] && process.argv[1].endsWith("seed-sanqualp.ts")) {
  seedSanqualp()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error("❌ Failed to seed SanQALP event:", err);
      process.exit(1);
    });
}
