import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import eventsRouter from "./events";
import paymentsRouter from "./payments";
import participantsRouter from "./participants";
import assignmentsRouter from "./assignments";
import filesRouter from "./files";
import agendaRouter from "./agenda";
import foodRouter from "./food";
import attendanceRouter from "./attendance";
import dashboardRouter from "./dashboard";
import tracksRouter from "./tracks";
import scientificRouter from "./scientific";
import settingsRouter from "./settings";
import systemUsersRouter from "./system-users";
import goodiesRouter from "./goodies";
import scanRouter from "./scan";
import submissionsRouter from "./submissions";
import sessionsRouter from "./sessions";
import onspotRouter from "./onspot";
import metricsRouter from "./metrics";
import timetableRouter from "./timetable";
import personalDetailsRouter from "./personal-details";
import rsvpRouter from "./rsvp";
import whatsappRouter from "./whatsapp";
import syncSessionsRouter from "./sync-sessions";
import walletRouter from "./wallet";
import idCardDesignsRouter from "./id-card-designs";
import chatRouter from "./chat";
import certificatesRouter from "./certificates";
import feedbackRouter from "./feedback";
import groupsRouter from "./groups";
import { startRsvpScheduler } from "../lib/rsvp-scheduler";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(eventsRouter);
router.use(paymentsRouter);
router.use(participantsRouter);
router.use(assignmentsRouter);
router.use(filesRouter);
router.use(agendaRouter);
router.use(foodRouter);
router.use(attendanceRouter);
router.use(dashboardRouter);
router.use(tracksRouter);
router.use(scientificRouter);
router.use(settingsRouter);
router.use(systemUsersRouter);
router.use(goodiesRouter);
router.use(scanRouter);
router.use(submissionsRouter);
router.use(sessionsRouter);
router.use(onspotRouter);
router.use(metricsRouter);
router.use(timetableRouter);
router.use(personalDetailsRouter);
router.use(rsvpRouter);
router.use(whatsappRouter);
router.use(syncSessionsRouter);
router.use(walletRouter);
router.use(idCardDesignsRouter);
router.use(chatRouter);
router.use(certificatesRouter);
router.use(feedbackRouter);
router.use(groupsRouter);

// Initialize WhatsApp RSVP auto-sending scheduler (runs every 60 seconds)
startRsvpScheduler();

export default router;
